# Generated by Django 5.1 on 2024-08-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card_Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='card_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crash_cards.card_back'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crash_cards.card_front'),
        ),
    ]
