# Generated by Django 5.1 on 2024-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_cards', '0002_card_back_card_front_remove_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_back',
            field=models.TextField(default='No Answer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_front',
            field=models.TextField(default='No Question'),
        ),
        migrations.DeleteModel(
            name='Card_Back',
        ),
        migrations.DeleteModel(
            name='Card_Front',
        ),
    ]
