# Generated by Django 5.1 on 2024-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_cards', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(to='crash_cards.card')),
            ],
        ),
    ]
