# Generated by Django 5.1 on 2024-08-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_cards', '0005_slidedeck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideDeck',
            new_name='CardDeck',
        ),
    ]
