# Generated by Django 5.1 on 2024-08-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_cards', '0006_rename_slidedeck_carddeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
    ]
